
# Netlify configuration file

[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proper MIME type handling
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/*"
  [headers.values]
    Content-Type = "application/javascript"
